import BlogImg1 from "../../images/blog-img08.jpg";
import BlogImg2 from "../../images/blog-img09.jpg";
import BlogImg3 from "../../images/blog-img10.png";
import BlogImg4 from "../../images/blog-img11.jpg";
let BlogItems = [
    {
       id:1,
       type:"daily",
       info:"日常学习类的哈哈哈哈啊哈哈哈哈哈哈哈哈哈哈",
       tag:"React",
       background:{BlogImg1},
    },
    {
        id:2,
        type:"tech",
        info:"日常学习类的哈哈哈哈啊哈哈哈哈哈哈哈哈哈哈",
        tag:"React",
        background:{BlogImg1},
     },
     {
        id:3,
        type:"daily",
        info:"日常学习类的哈哈哈哈啊哈哈哈哈哈哈哈哈哈哈",
        tag:"React",
        background:"../../images/blog-img09.jpg",
     },
     {
        id:4,
        type:"tech",
        info:"日常学习类的哈哈哈哈啊哈哈哈哈哈哈哈哈哈哈",
        tag:"React",
        background:"../../images/blog-img05.jpg",
     },
     {
        id:5,
        type:"good",
        info:"日常学习类的哈哈哈哈啊哈哈哈哈哈哈哈哈哈哈",
        tag:"React",
        background:"../../images/blog-img02.jpg",
     },
     {
        id:6,
        type:"good",
        info:"日常学习类的哈哈哈哈啊哈哈哈哈哈哈哈哈哈哈",
        tag:"React",
        background:"../../images/blog-img01.jpg",
     },
     {
        id:7,
        type:"bug",
        info:"日常学习类的哈哈哈哈啊哈哈哈哈哈哈哈哈哈哈",
        tag:"React",
        background:"../../images/blog-img09.jpg",
     },
     {
        id:8,
        type:"bug",
        info:"日常学习类的哈哈哈哈啊哈哈哈哈哈哈哈哈哈哈",
        tag:"React",
        background:"../../images/blog-img08.jpg",
     },
     {
        id:9,
        type:"good",
        info:"日常学习类的哈哈哈哈啊哈哈哈哈哈哈哈哈哈哈",
        tag:"React",
        background:"../../images/blog-img10.jpg",
     },
     {
        id:10,
        type:"daily",
        info:"日常学习类的哈哈哈哈啊哈哈哈哈哈哈哈哈哈哈",
        tag:"React",
        background:"../../images/blog-img10.jpg",
     },
     {
        id:11,
        type:"good",
        info:"日常学习类的哈哈哈哈啊哈哈哈哈哈哈哈哈哈哈",
        tag:"React",
        img:"../../images/blog-img09.jpg",
     },
     {
        id:12,
        type:"tech",
        info:"日常学习类的哈哈哈哈啊哈哈哈哈哈哈哈哈哈哈",
        tag:"React",
        background:"../../images/blog-img09.jpg",
     },
];
export default BlogItems;